spring:
  datasource:
    url: jdbc:mysql://yourip/TESTDB?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 3MB

server:
  port: 12345

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml    # mapper映射文件位置
  type-aliases-package: com.ddbs.pojo    # 实体类所在的位置
  config-location: classpath:mybatis/mybatis-config.xml

system-params:
  company-staff: 10003

#configuration:
#  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句


